<a href="https://colab.research.google.com/github/reidnersousa/IFB_Analise_Algoritmo_2024/blob/main/Ordena%C3%A7%C3%A3o_por_sele%C3%A7%C3%A3o_de_raiz_quadrada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

Etapa 1

In [ ]:
import numpy as np
import math
import random


def gerando_amostra(N):
  sequencia = np.random.randint(1, N + 1, N)
  return sequencia
N =  100

vetor_entrada_100 = gerando_amostra(N)
#### Dividindo o vetor em sqrt(N) onde N é tamanho do vetor
print(vetor_entrada_100)
qtd_partes = np.sqrt(N)
print("qtd_partes",qtd_partes)

### Caso o tamanho do vetor não seja múltiplo de sqrt(N)


if N % qtd_partes ==0:
  print("é múltiplo")

  lista=[]
  j=0
  for i in range(0,int(qtd_partes)):
    j = j+1
    print("j",j,"i",i)
    corte = vetor_entrada_100[int(qtd_partes)*i:int(qtd_partes)*j]
    print("corte",corte)
    lista.append(corte)

  print("lista",lista)

else:
  ### a ultima parte terá tamanho (N mod chão(sqrt(N)))
  chao_sqrt_n  = math.floor(qtd_partes)
  print(chao_sqrt_n)
  ultima_parte_tamanho =  N % chao_sqrt_n
  print("ultima_parte tamanho",ultima_parte_tamanho)


  lista=[]
  j=0
  for i in range(0,int(qtd_partes)):
    j = j+1
    print("j",j,"i",i)
    corte = vetor_entrada_100[int(qtd_partes)*i:int(qtd_partes)*j]
    print("corte",corte)
    lista.append(corte)
  corte_ultimo = vetor_entrada_100[int(qtd_partes)*j:]
  print("corte_ultimo",corte_ultimo)
  lista.append(corte_ultimo)
  print("lista",lista)



def eh_multiplo(N,qtd_partes):
  return N % qtd_partes ==0

eh_multiplo(N,qtd_partes)




[64  6 42 95 60 83 97 14 22 31 76 90 48  7 94 17 49 47  6 13 76 50 61 43
 70 73 24 47 19 46  2 29 81 33 11 67 30 92 86 91 80 67 42 17  3 91 47 88
 95 79 97 94 43 70 20 86 70  2 25 67 67 38 57 95 72  2 22 29 94  5 42 45
 29 95 53 91 13 85 63 43 89 71 94 75 53 51 76  1 38  1 68 17 10 67 83 49
 34 66 85 26]
qtd_partes 10.0
é múltiplo
j 1 i 0
corte [64  6 42 95 60 83 97 14 22 31]
j 2 i 1
corte [76 90 48  7 94 17 49 47  6 13]
j 3 i 2
corte [76 50 61 43 70 73 24 47 19 46]
j 4 i 3
corte [ 2 29 81 33 11 67 30 92 86 91]
j 5 i 4
corte [80 67 42 17  3 91 47 88 95 79]
j 6 i 5
corte [97 94 43 70 20 86 70  2 25 67]
j 7 i 6
corte [67 38 57 95 72  2 22 29 94  5]
j 8 i 7
corte [42 45 29 95 53 91 13 85 63 43]
j 9 i 8
corte [89 71 94 75 53 51 76  1 38  1]
j 10 i 9
corte [68 17 10 67 83 49 34 66 85 26]
lista [array([64,  6, 42, 95, 60, 83, 97, 14, 22, 31]), array([76, 90, 48,  7, 94, 17, 49, 47,  6, 13]), array([76, 50, 61, 43, 70, 73, 24, 47, 19, 46]), array([ 2, 29, 81, 33, 11, 67, 30, 92, 86, 91]), arr

True

Etapa 2

In [ ]:
lista


[array([70, 81, 41, 77, 14,  9, 33, 63, 68, 29]),
 array([26, 63, 93, 83,  9, 56, 20,  6, 73,  8]),
 array([49, 91, 62, 48, 88, 34, 56, 86, 14, 44]),
 array([88, 29, 31, 66, 81, 56,  8, 86, 24, 63]),
 array([68, 62, 41, 75, 53, 41, 81, 34, 32, 61]),
 array([ 52,  26,  71,  37, 100,  73,  17, 100,  91,  13]),
 array([81, 59, 90, 57, 80, 82, 72, 18, 84, 30]),
 array([ 2, 54,  5, 11, 80, 50, 70, 19,  6, 48]),
 array([43, 81, 23, 47, 61, 21,  1, 69, 42, 66]),
 array([82, 34, 34, 40, 83, 40, 75, 28, 13, 24])]

In [ ]:
## 2. Encontre o maior elemento ei de cada parte Vi , com 1 ≤ i ≤ k.

lista[0]
lista_maiores = []
for i in lista:
  maior_elemento=np.max(i)

  lista_maiores.append(maior_elemento)

lista_maiores

[81, 93, 91, 88, 81, 100, 90, 80, 81, 83]

Etapa 3

In [ ]:
#Pegue o maior elemento dentre e1 . . . ek e o insira no vetor solução.
# Se o maiorelemento for o ej, então ele deve ser descartado da parte Vj.
vetor_solucao =[]
vetor_solucao.append(np.max(lista_maiores))
lista_maiores.remove(np.max(lista_maiores))
print(lista_maiores)
vetor_solucao

[81, 88, 81, 80, 81, 83]


[90]

Etapa 4

In [51]:
def bubbleSort(array):
    for i in range(len(array)-1,0,-1):
      #print(i)
      for j in range(i):
        #print(">>",i)
        if array[j]>array[j+1]:
          temp = array[j]
          array[j] = array[j+1]

          array[j+1] = temp


alist = [54,26,93,17,77,31,44,55,20]
bubbleSort(alist)
print(alist)


[17, 20, 26, 31, 44, 54, 55, 77, 93]


In [55]:
#Repita os passos de 2 a 3 até que todas as partes estejam vazias

class OrdenacaoRaizQuadrada:
  def __init__(self,vetor):
    self.vetor = vetor
    self.N = len(vetor)
    self.vetor_solucao =[]

  def bubbleSort(self,array):
    for i in range(len(array)-1,0,-1):
      #print(i)
      for j in range(i):
        #print(">>",i)
        if array[j]>array[j+1]:
          temp = array[j]
          array[j] = array[j+1]
          array[j+1] = temp

  def etapa_1(self):
    qtd_partes = np.sqrt(self.N)
    if self.N % qtd_partes == 0:
      lista = []
      j=0
      for i in range(0,int(qtd_partes)):
        j = j+1

        corte = vetor_entrada_100[int(qtd_partes)*i:int(qtd_partes)*j]

        lista.append(corte)

    else:
      ### a ultima parte terá tamanho (N mod chão(sqrt(N)))
      chao_sqrt_n  = math.floor(qtd_partes)
      ultima_parte_tamanho =  N % chao_sqrt_n



      lista=[]
      j=0
      for i in range(0,int(qtd_partes)):
        j = j+1

        corte = vetor_entrada_100[int(qtd_partes)*i:int(qtd_partes)*j]

        lista.append(corte)
      corte_ultimo = vetor_entrada_100[int(qtd_partes)*j:]

      lista.append(corte_ultimo)


    return lista
    ## 2. Encontre o maior elemento ei de cada parte Vi , com 1 ≤ i ≤ k.
  def etapa_2(self):

    lista_maiores = []
    for i in self.array_de_array:
      if i.size>0:
        ### Utilizar o bubble sort aqui
        self.bubbleSort(i)

        maior_elemento=i[-1]
        lista_maiores.append(maior_elemento)
      else :
        pass
    lista_maiores = np.array(lista_maiores)
    self.lista_maiores= lista_maiores

  ### Ajusta etapa 3
  def etapa_3(self):

    vetor_solucao = []
    maior_numero =  np.max(self.lista_maiores)


    for i,sub_array in enumerate(self.array_de_array):
      for j,numero in enumerate(sub_array):

        if numero == maior_numero:

          index_a_remover = np.where(sub_array==maior_numero)[0][0]


          self.array_de_array[i] = np.delete(sub_array, index_a_remover)
          break ## tirando  o break ele remove tudo



    self.vetor_solucao.append(np.max(self.lista_maiores))








  def etapa_4(self):
    print("entrei aqui")
    print(self.vetor)
    print(self.N)
    self.array_de_array=self.etapa_1()

    is_array_cheia = True

    while is_array_cheia == True:

      if  not self.array_de_array :

        is_array_cheia = False
      else:

        #print("cheio")

        #print(self.array_de_array)

        self.etapa_2()
        #print(self.lista_maiores)  ### array([8, 8, 9, 7])
        self.etapa_3()
        #print(self.vetor_solucao) ##[9]
        self.array_de_array = list(filter(np.any,self.array_de_array))

    print(self.array_de_array,">>",self.vetor_solucao)


teste = OrdenacaoRaizQuadrada(vetor_entrada_100)
teste.array_de_array = teste.etapa_1()
teste.etapa_2()



In [56]:
print(vetor_entrada_100)
teste2_etapa_4 =OrdenacaoRaizQuadrada(vetor_entrada_100)
teste2_etapa_4.etapa_4()

[ 6 14 22 31 42 60 64 83 95 97  6  7 13 17 47 48 49 76 90 94 19 24 43 46
 47 50 61 70 73 76  2 11 29 30 33 67 81 86 91 92  3 17 42 47 67 79 80 88
 91 95  2 20 25 43 67 70 70 86 94 97  2  5 22 29 38 57 67 72 94 95 13 29
 42 43 45 53 63 85 91 95  1  1 38 51 53 71 75 76 89 94 10 17 26 34 49 66
 67 68 83 85]
entrei aqui
[ 6 14 22 31 42 60 64 83 95 97  6  7 13 17 47 48 49 76 90 94 19 24 43 46
 47 50 61 70 73 76  2 11 29 30 33 67 81 86 91 92  3 17 42 47 67 79 80 88
 91 95  2 20 25 43 67 70 70 86 94 97  2  5 22 29 38 57 67 72 94 95 13 29
 42 43 45 53 63 85 91 95  1  1 38 51 53 71 75 76 89 94 10 17 26 34 49 66
 67 68 83 85]
100
[] >> [97, 95, 94, 92, 91, 90, 89, 88, 86, 85, 83, 81, 80, 79, 76, 75, 73, 72, 71, 70, 70, 68, 67, 66, 64, 63, 61, 60, 57, 53, 51, 50, 49, 48, 47, 46, 45, 43, 42, 38, 34, 33, 31, 30, 29, 26, 25, 24, 22, 20, 19, 17, 14, 13, 11, 10, 7, 6, 5, 3, 2, 1, 1]
